apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: zeus
  name: zeus-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: zeus
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: zeus-role
  apiGroup: rbac.authorization.k8s.io
