apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: zeus
  name: zeus-role
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "pods" ]
    verbs: [get, watch, list, patch]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "configmaps" ]
    verbs: [ get, watch, list ]
