apiVersion: v1
kind: Service
metadata:
  name: zeus-backend-layout
spec:
  selector:
    app: zeus-backend-layout
  type: NodePort
  ports:
      - name: http
        protocol: TCP
        port: 8000
        targetPort: 8000
        nodePort: 30000
      - name: grpc
        protocol: TCP
        port: 9000
        targetPort: 9000
        nodePort: 30001

  